BEGIN;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS "avatarUrl" VARCHAR(500);

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS "birthday" DATE;

ALTER TABLE users 
ADD COLUMN IF NOT EXISTS "bio" TEXT;

COMMIT;
